electron/app/js/appUpdater.js
webui/src/js/views/app-update-dialog.html

Also fix button hiding problem.

Quit and install in update-downloaded event

---

documentation/1.0/content/release notes/release-notes.md
documentation/1.0/content/setup/install.md

Doc for Application Update dialog.

App Updates

---

webui/src/js/utils/ingress-routes-helper.js

This PR fixes the external load balancer url construction error:- Extra slash in url & load balancer status ingress is an array instead of an object.

Fix external load balancer url detection logic

---

documentation/1.0/content/setup/install.md
documentation/1.0/content/setup/prerequisites.md

First cut at adding information for a Linux install.

linux install

---

README.md
documentation/1.0/content/_index.md
documentation/1.0/content/setup/install.md
documentation/1.0/content/setup/prerequisites.md

AppImage info, cleanup Prereqs, and edit Get Help with Slack channel info.

additional install info

---

README.md
documentation/1.0/content/_index.md

To newly created #weblogic-kubernetes-toolkit

change Slack channel name

---

documentation/staging/content/navigate/image.md
documentation/staging/content/navigate/kubernetes/k8s-ingress-controller.md
documentation/staging/content/navigate/kubernetes/k8s-weblogic-domain.md
documentation/staging/content/navigate/kubernetes/k8s-wko.md
documentation/staging/content/release notes/_index.md

Fist draft doc for four new button actions.

doc new button actions

---

documentation/staging/content/navigate/image.md
documentation/staging/content/navigate/kubernetes/k8s-ingress-controller.md
documentation/staging/content/navigate/kubernetes/k8s-weblogic-domain.md
documentation/staging/content/navigate/kubernetes/k8s-wko.md
documentation/staging/content/release notes/_index.md

Doc for additional functionality to uninstall actions and for WKTUI-289 Document implications of using WDT 2.0 bundled with WKTUI 1.1.0.

doc updates

---

electron/app/locales/en/webui.json
electron/package.json
webui/package-lock.json
webui/package.json
webui/src/index.html
webui/src/js/viewModels/app-main.js
webui/src/js/viewModels/domain-design-view.js
webui/src/js/views/app-main.html
webui/src/js/views/domain-design-view.html

Also fixed the app-main page to display the correct copyright years.

adding button to regenerate the runtime encryption secret value

---

README.md

Updated the Related Project links in the README file to point to the related repo projects.

update repo doc links

---

electron/app/js/project.js

Resolve problem when "Save As..." saves to a project file in a different directory.

Always update project file for window during save

---

documentation/1.1/content/setup/install.md
documentation/1.1/content/setup/prerequisites.md
electron/package.json

Add required package to package.json and update install/pre-req documentation.

Fix install pkg doc

---

webui/src/js/viewModels/domain-design-view.js
webui/src/js/viewModels/image-design-view-impl.js

Wait for aux image tag to initialize before refreshing.
Listen for aux image changes for open/close project.

Image usability fixes

---

webui/src/js/models/wdt-model-definition.js

Assign default name to archive file if any archive roots are present.
Internal Jira WKTUI-322

Include archive in "Save As..." result

---

electron/app/js/project.js

Set window title on ready-to-show

Initialize correct window for new project

---

wktui.wptg

Configuration for resource bundle translation.

added configuration for i18n translation

---

webui/src/js/viewModels/model-design-view.js

- Added missing semi-colon on line# 169

Fix variable lists management in WRC integ

---

webui/src/css/app.css
webui/src/js/viewModels/vz-ingress-trait-rule-edit-dialog.js
webui/src/js/views/vz-application-design-view.html
webui/src/js/views/vz-ingress-trait-rule-edit-dialog.html

Also display "Add Component" button beside to heading

Display empty input box for unspecified number values

---

documentation/staging/1.3/content/navigate/verrazzano/vz-application.md
documentation/staging/1.3/content/navigate/verrazzano/vz-component.md

Few description enhancements, improve text

enhance VZ content

---

webui/src/js/utils/ingress-controller-installer.js

Adding ingress image pull secret only when the user asks to use it

---

electron/app/main.js

fixing argument matching problem causing Verrazzano application status calls to fail
